# Generated by Django 4.0.2 on 2024-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_groups_alter_driver_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufactured',
            new_name='manufacturer',
        ),
    ]
